name: grocery_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.12+4
  http: ^0.12.2
  dots_indicator: ^1.2.0
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.4
  firebase_core: ^0.5.3
  provider: ^4.3.2+3
  geolocator: ^6.1.13
  google_maps_flutter: ^1.0.6
  geocoder: ^0.2.1
  flutter_spinkit: ^4.1.2+1
  carousel_slider: ^2.3.1
  image_picker: ^0.6.7+17
  email_validator: '^1.0.5'
  location: ^3.2.1
  firebase_storage: ^5.2.0
  paginate_firestore: ^0.2.2
  persistent_bottom_nav_bar: ^3.1.0
  flutter_slider_drawer: ^1.2.1
  flutter_easyloading: ^2.2.2
  url_launcher: ^5.7.10
  map_launcher: ^1.1.2
  expandable_text: 2.0.0
  toggle_bar: ^1.0.0
  dotted_border: ^1.0.7
  chips_choice: ^2.0.1
  stripe_payment: ^1.0.10
  flutter_credit_card: ^0.1.4
  flutter_slidable: ^0.5.7
  search_page: ^1.4.0+1
  webview_flutter: ^1.0.7
  http_auth: ^0.3.2
  flutter_echarts: ^1.5.0
  syncfusion_flutter_charts: ^18.4.49
  flutter_dialogflow: ^0.1.3
  flutter_chat_bubble: ^1.0.2
  custom_pop_up_menu: ^1.1.2
  
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/fluttergroceryappchatbot-sxau-be63b2ec9e8d.json

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Bold.ttf
          weight: 700
        - asset: fonts/Lato-Regular.ttf

    - family: Anton
      fonts:
        - asset: fonts/Anton-Regular.ttf
